package jp.mydns.kokoichi0206.gmail

import jp.mydns.kokoichi0206.gmail.model.MailData

val mailList = listOf(
    MailData(
        id = 1,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 2,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 3,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 4,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 5,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 6,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 7,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 8,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 9,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 10,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 11,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 12,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 13,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 14,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
    MailData(
        id = 15,
        userName = "John Doe",
        subject = "Email regarding something urgent",
        body = "Your credit card is out of date",
        timeStamp = "12:34",
    ),
)
