package jp.mydns.kokoichi0206.jetpackglance

import android.os.Build
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.DpSize
import androidx.compose.ui.unit.dp
import androidx.glance.*
import androidx.glance.layout.*
import androidx.glance.text.FontWeight
import androidx.glance.text.Text
import androidx.glance.text.TextStyle
import androidx.core.content.ContextCompat.startActivity

import android.content.Intent
import android.util.Log
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.ui.res.fontResource
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat
import androidx.glance.action.*
import androidx.glance.appwidget.*
import androidx.glance.appwidget.action.actionStartActivity
import androidx.glance.appwidget.lazy.LazyColumn
import androidx.glance.unit.ColorProvider


class GreetingsWidget(private val name: String) : GlanceAppWidget() {

    companion object {
        private val SMALL_SQUARE = DpSize(100.dp, 100.dp)
        private val HORIZONTAL_RECTANGLE = DpSize(250.dp, 100.dp)
        private val BIG_SQUARE = DpSize(250.dp, 250.dp)
    }

//    override val sizeMode = SizeMode.Responsive(
//        sizes = setOf(SMALL_SQUARE, HORIZONTAL_RECTANGLE, BIG_SQUARE)
//    )

    override val sizeMode = SizeMode.Exact

    @Composable
    override fun Content() {
        val size = LocalSize.current
        val context = LocalContext.current

        if (size.height > SMALL_SQUARE.height) {
            Text("xxx")
        }

        Column(
            modifier = GlanceModifier
                .background(Color.White)
                .fillMaxSize()
        ) {
            val col = ((size.height - 90.dp) / 100.dp).toInt() + 1
            val row = ((size.width - 57.dp) / 70.dp).toInt() + 1
            Log.d("hoge", "size.width: ${size.width}")
            Log.d("hoge", "row: $row")
            Log.d("hoge", "size.height: ${size.height}")
            Log.d("hoge", "col: $col")
            for (i in 1..col) {
                Row(
                    modifier = GlanceModifier
                        .fillMaxWidth()
                        .defaultWeight(),
                ) {
                    for (j in 1..row) {
                        Box(
                            modifier = GlanceModifier
                                .defaultWeight()
                                .fillMaxHeight(),
                            contentAlignment = Alignment.Center,
                        ) {


                            val position = "$j$i"

//
                            Text(
//                                modifier = GlanceModifier
//                                    .clickable(
//                                        kotlin.run {
//
//                                            val intent = Intent(context, MainActivity::class.java)
//                                            intent.putExtra("POSITION", position)
//                                            actionStartActivity(intent)
//                                        }
////                                        actionStartActivity(intent)
//                                    ),
                                text = position,
                            )
////                            Button(
////                                text = position,
////                                modifier = GlanceModifier.height(48.dp),
////                                onClick = actionStartActivity<MainActivity>()
//////                                onClick = actionStartActivity<MainActivity>(
//////                                    parameters = actionParametersOf(
//////                                        ActionParameters.Pair(
//////                                            ActionParameters.Key("hoge"), "hoge"
//////                                        )
////////                                        ActionParameters.Pair(
////////                                            ActionParameters.Key("hoge"),
////////                                            "hoge"
////////                                        )
//////                                    )
//////                                )
////                            )
//
//                            Image(
//                                modifier = GlanceModifier
//                                    .size(60.dp),
//                                provider = ImageProvider(R.drawable.gan),
//                                contentDescription = "image generated by gan"
//                            )
//                        }
//                    }
//                }
//            }
//        }

//  計算に使ったメモ
//        height: 90.1 -> 196.3 -> 302.5
//        106.2
//        -90
//        width: 203.2
//        73.1
//-57
                        }
                    }
                }
            }
        }
    }
}

@Composable
fun GlanceModifier.appWidgetBackgroundRadius(): GlanceModifier {
    return if (Build.VERSION.SDK_INT >= 31) {
        this.cornerRadius(android.R.dimen.system_app_widget_background_radius)
    } else {
        this.cornerRadius(16.dp)
    }
}
